url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "N3TS3ND" # the name of your site, e.g. ACME Corp.

disqus:
    shortname: n3ts3nd

plugins:
    - jekyll-seo-tag