title: "N3TS3ND"

#about: ""
markdown: kramdown
url: ""
baseurl: ""
disqus_short_name: n3ts3nd

plugins: 
  - jekyll-paginate
  - jemoji
  
paginate_path: "/page:num/"

paginate: 5

main_toc:
  - title: Home
    url: ""
  # - title: About
  #   url: "about"
  # - title: Author
  #   url: "author"

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"

permalink: /:slug